// <auto-generated />
using System;
using Final_Project.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Project.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20251206110358_frist")]
    partial class frist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final_Project.Model.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Present")
                        .HasColumnType("bit");

                    b.Property<int>("Professor_Id")
                        .HasColumnType("int");

                    b.Property<int>("Student_Id")
                        .HasColumnType("int");

                    b.Property<int>("Subject_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Professor_Id");

                    b.HasIndex("Student_Id");

                    b.HasIndex("Subject_Id");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 12, 4, 13, 3, 58, 177, DateTimeKind.Local).AddTicks(8742),
                            Present = true,
                            Professor_Id = 1,
                            Student_Id = 1,
                            Subject_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 12, 4, 13, 3, 58, 177, DateTimeKind.Local).AddTicks(8760),
                            Present = false,
                            Professor_Id = 1,
                            Student_Id = 2,
                            Subject_Id = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 12, 5, 13, 3, 58, 177, DateTimeKind.Local).AddTicks(8762),
                            Present = true,
                            Professor_Id = 4,
                            Student_Id = 3,
                            Subject_Id = 2
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 12, 5, 13, 3, 58, 177, DateTimeKind.Local).AddTicks(8764),
                            Present = true,
                            Professor_Id = 4,
                            Student_Id = 4,
                            Subject_Id = 2
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 12, 3, 13, 3, 58, 177, DateTimeKind.Local).AddTicks(8766),
                            Present = false,
                            Professor_Id = 2,
                            Student_Id = 5,
                            Subject_Id = 3
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 12, 3, 13, 3, 58, 177, DateTimeKind.Local).AddTicks(8769),
                            Present = true,
                            Professor_Id = 2,
                            Student_Id = 1,
                            Subject_Id = 3
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 12, 2, 13, 3, 58, 177, DateTimeKind.Local).AddTicks(8770),
                            Present = true,
                            Professor_Id = 6,
                            Student_Id = 2,
                            Subject_Id = 4
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 12, 2, 13, 3, 58, 177, DateTimeKind.Local).AddTicks(8772),
                            Present = false,
                            Professor_Id = 6,
                            Student_Id = 3,
                            Subject_Id = 4
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2025, 12, 1, 13, 3, 58, 177, DateTimeKind.Local).AddTicks(8774),
                            Present = true,
                            Professor_Id = 3,
                            Student_Id = 4,
                            Subject_Id = 5
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2025, 12, 1, 13, 3, 58, 177, DateTimeKind.Local).AddTicks(8776),
                            Present = false,
                            Professor_Id = 3,
                            Student_Id = 5,
                            Subject_Id = 5
                        });
                });

            modelBuilder.Entity("Final_Project.Model.Professor", b =>
                {
                    b.Property<int>("Professor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Professor_id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Phone")
                        .HasColumnType("bigint");

                    b.Property<string>("Pro_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pro_code")
                        .HasColumnType("int");

                    b.HasKey("Professor_id");

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Professor_id = 1,
                            Department = "CS",
                            Email = "ahmed@gmail.com",
                            Gender = "Male",
                            Password = "pass123",
                            Phone = 1253456789L,
                            Pro_Name = "Dr. Ahmed",
                            Pro_code = 201
                        },
                        new
                        {
                            Professor_id = 2,
                            Department = "IT",
                            Email = "mona@gmail.com",
                            Gender = "Female",
                            Password = "mona321",
                            Phone = 1287654321L,
                            Pro_Name = "Dr. Mona",
                            Pro_code = 202
                        },
                        new
                        {
                            Professor_id = 3,
                            Department = "IS",
                            Email = "tarek@gmail.com",
                            Gender = "Male",
                            Password = "tarek456",
                            Phone = 1171222333L,
                            Pro_Name = "Dr. Tarek",
                            Pro_code = 203
                        },
                        new
                        {
                            Professor_id = 4,
                            Department = "CS",
                            Email = "salma@gmail.com",
                            Gender = "Female",
                            Password = "salma789",
                            Phone = 1284555666L,
                            Pro_Name = "Dr. Salma",
                            Pro_code = 204
                        },
                        new
                        {
                            Professor_id = 5,
                            Department = "IT",
                            Email = "mostafa@gmail.com",
                            Gender = "Male",
                            Password = "mostafa000",
                            Phone = 1077888999L,
                            Pro_Name = "Dr. Mostafa",
                            Pro_code = 205
                        },
                        new
                        {
                            Professor_id = 6,
                            Department = "CS",
                            Email = "lina@gmail.com",
                            Gender = "Female",
                            Password = "lina123",
                            Phone = 222333444L,
                            Pro_Name = "Dr. Lina",
                            Pro_code = 206
                        });
                });

            modelBuilder.Entity("Final_Project.Model.Student", b =>
                {
                    b.Property<int>("Student_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_id"));

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Phone")
                        .HasColumnType("bigint");

                    b.Property<string>("St_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("St_code")
                        .HasColumnType("int");

                    b.HasKey("Student_id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Student_id = 1,
                            Department = "CS",
                            Email = "mostafa@gmail.com",
                            Gender = "Male",
                            Password = "123456",
                            Phone = 1234567894L,
                            St_Name = "Mostafa",
                            St_code = 111
                        },
                        new
                        {
                            Student_id = 2,
                            Department = "IT",
                            Email = "sara@gmail.com",
                            Gender = "Female",
                            Password = "abcdef",
                            Phone = 1098765432L,
                            St_Name = "Sara",
                            St_code = 112
                        },
                        new
                        {
                            Student_id = 3,
                            Department = "CS",
                            Email = "youssef@gmail.com",
                            Gender = "Male",
                            Password = "pass123",
                            Phone = 1112223335L,
                            St_Name = "Youssef",
                            St_code = 113
                        },
                        new
                        {
                            Student_id = 4,
                            Department = "IS",
                            Email = "nada@gmail.com",
                            Gender = "Female",
                            Password = "nada321",
                            Phone = 1244555666L,
                            St_Name = "Nada",
                            St_code = 114
                        },
                        new
                        {
                            Student_id = 5,
                            Department = "CS",
                            Email = "ahmed@gmail.com",
                            Gender = "Male",
                            Password = "omar789",
                            Phone = 1577888999L,
                            St_Name = "Ahmed",
                            St_code = 115
                        });
                });

            modelBuilder.Entity("Final_Project.Model.StudentSubject", b =>
                {
                    b.Property<int?>("Student_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Subject_Id")
                        .HasColumnType("int");

                    b.HasKey("Student_Id", "Subject_Id");

                    b.HasIndex("Subject_Id");

                    b.ToTable("StudentSubjects");

                    b.HasData(
                        new
                        {
                            Student_Id = 1,
                            Subject_Id = 1
                        },
                        new
                        {
                            Student_Id = 1,
                            Subject_Id = 3
                        },
                        new
                        {
                            Student_Id = 2,
                            Subject_Id = 1
                        },
                        new
                        {
                            Student_Id = 2,
                            Subject_Id = 4
                        },
                        new
                        {
                            Student_Id = 3,
                            Subject_Id = 2
                        },
                        new
                        {
                            Student_Id = 3,
                            Subject_Id = 4
                        },
                        new
                        {
                            Student_Id = 4,
                            Subject_Id = 2
                        },
                        new
                        {
                            Student_Id = 4,
                            Subject_Id = 5
                        },
                        new
                        {
                            Student_Id = 5,
                            Subject_Id = 3
                        },
                        new
                        {
                            Student_Id = 5,
                            Subject_Id = 5
                        });
                });

            modelBuilder.Entity("Final_Project.Model.Subject", b =>
                {
                    b.Property<int>("Sub_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sub_ID"));

                    b.Property<int?>("Professor_Id")
                        .HasColumnType("int");

                    b.Property<string>("Sub_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sub_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sub_ID");

                    b.HasIndex("Professor_Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Sub_ID = 1,
                            Professor_Id = 1,
                            Sub_Code = "CS101",
                            Sub_Name = "OOP"
                        },
                        new
                        {
                            Sub_ID = 2,
                            Professor_Id = 4,
                            Sub_Code = "CS102",
                            Sub_Name = "Databases"
                        },
                        new
                        {
                            Sub_ID = 3,
                            Professor_Id = 2,
                            Sub_Code = "IT201",
                            Sub_Name = "Networks"
                        },
                        new
                        {
                            Sub_ID = 4,
                            Professor_Id = 6,
                            Sub_Code = "CS202",
                            Sub_Name = "Algorithms"
                        },
                        new
                        {
                            Sub_ID = 5,
                            Professor_Id = 3,
                            Sub_Code = "IS301",
                            Sub_Name = "Information Security"
                        });
                });

            modelBuilder.Entity("Final_Project.Model.Attendance", b =>
                {
                    b.HasOne("Final_Project.Model.Professor", "Professor")
                        .WithMany("Attendances")
                        .HasForeignKey("Professor_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Final_Project.Model.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Final_Project.Model.Subject", "Subject")
                        .WithMany("Attendances")
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Final_Project.Model.StudentSubject", b =>
                {
                    b.HasOne("Final_Project.Model.Student", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Final_Project.Model.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Final_Project.Model.Subject", b =>
                {
                    b.HasOne("Final_Project.Model.Professor", "Professor")
                        .WithMany("Subjects")
                        .HasForeignKey("Professor_Id");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Final_Project.Model.Professor", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Final_Project.Model.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("Final_Project.Model.Subject", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("StudentSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
