// <auto-generated />
using System;
using Final_Project.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Project.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20260406162844_hl")]
    partial class hl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final_Project.Model.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Present")
                        .HasColumnType("bit");

                    b.Property<int>("Professor_Id")
                        .HasColumnType("int");

                    b.Property<int>("Student_Id")
                        .HasColumnType("int");

                    b.Property<int>("Subject_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Professor_Id");

                    b.HasIndex("Student_Id");

                    b.HasIndex("Subject_Id");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 4, 4, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8612),
                            Present = true,
                            Professor_Id = 1,
                            Student_Id = 1,
                            Subject_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 4, 4, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8634),
                            Present = false,
                            Professor_Id = 1,
                            Student_Id = 2,
                            Subject_Id = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 4, 5, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8636),
                            Present = true,
                            Professor_Id = 4,
                            Student_Id = 3,
                            Subject_Id = 2
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 4, 5, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8638),
                            Present = true,
                            Professor_Id = 4,
                            Student_Id = 4,
                            Subject_Id = 2
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2026, 4, 3, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8646),
                            Present = false,
                            Professor_Id = 2,
                            Student_Id = 5,
                            Subject_Id = 3
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2026, 4, 3, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8649),
                            Present = true,
                            Professor_Id = 2,
                            Student_Id = 1,
                            Subject_Id = 3
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2026, 4, 2, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8650),
                            Present = true,
                            Professor_Id = 6,
                            Student_Id = 2,
                            Subject_Id = 4
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2026, 4, 2, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8654),
                            Present = false,
                            Professor_Id = 6,
                            Student_Id = 3,
                            Subject_Id = 4
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2026, 4, 1, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8656),
                            Present = true,
                            Professor_Id = 3,
                            Student_Id = 4,
                            Subject_Id = 5
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2026, 4, 1, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8658),
                            Present = false,
                            Professor_Id = 3,
                            Student_Id = 5,
                            Subject_Id = 5
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2026, 4, 5, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8660),
                            Present = true,
                            Professor_Id = 1,
                            Student_Id = 6,
                            Subject_Id = 6
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2026, 4, 4, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8662),
                            Present = false,
                            Professor_Id = 6,
                            Student_Id = 7,
                            Subject_Id = 7
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2026, 4, 3, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8663),
                            Present = true,
                            Professor_Id = 3,
                            Student_Id = 8,
                            Subject_Id = 5
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2026, 4, 2, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8665),
                            Present = true,
                            Professor_Id = 4,
                            Student_Id = 9,
                            Subject_Id = 2
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2026, 4, 4, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8667),
                            Present = false,
                            Professor_Id = 2,
                            Student_Id = 10,
                            Subject_Id = 8
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2026, 4, 5, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8669),
                            Present = true,
                            Professor_Id = 7,
                            Student_Id = 11,
                            Subject_Id = 9
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2026, 4, 4, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8670),
                            Present = false,
                            Professor_Id = 8,
                            Student_Id = 12,
                            Subject_Id = 10
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2026, 4, 3, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8674),
                            Present = true,
                            Professor_Id = 9,
                            Student_Id = 13,
                            Subject_Id = 11
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2026, 4, 5, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8676),
                            Present = true,
                            Professor_Id = 7,
                            Student_Id = 14,
                            Subject_Id = 12
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2026, 4, 4, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8678),
                            Present = false,
                            Professor_Id = 7,
                            Student_Id = 15,
                            Subject_Id = 9
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2026, 4, 3, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8680),
                            Present = true,
                            Professor_Id = 8,
                            Student_Id = 16,
                            Subject_Id = 10
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2026, 4, 5, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8682),
                            Present = true,
                            Professor_Id = 9,
                            Student_Id = 17,
                            Subject_Id = 11
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2026, 4, 4, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8683),
                            Present = false,
                            Professor_Id = 7,
                            Student_Id = 18,
                            Subject_Id = 12
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2026, 4, 3, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8685),
                            Present = true,
                            Professor_Id = 7,
                            Student_Id = 19,
                            Subject_Id = 9
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2026, 4, 5, 18, 28, 44, 322, DateTimeKind.Local).AddTicks(8688),
                            Present = true,
                            Professor_Id = 8,
                            Student_Id = 20,
                            Subject_Id = 10
                        });
                });

            modelBuilder.Entity("Final_Project.Model.Professor", b =>
                {
                    b.Property<int>("Professor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Professor_id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Phone")
                        .HasColumnType("bigint");

                    b.Property<string>("Pro_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pro_code")
                        .HasColumnType("int");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Professor_id");

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Professor_id = 1,
                            Department = "CS",
                            Email = "ahmed@gmail.com",
                            Gender = "Male",
                            Password = "pass123",
                            Phone = 1253456789L,
                            Pro_Name = "Dr. Ahmed",
                            Pro_code = 201,
                            Role = "Professor"
                        },
                        new
                        {
                            Professor_id = 2,
                            Department = "IT",
                            Email = "mona@gmail.com",
                            Gender = "Female",
                            Password = "mona321",
                            Phone = 1287654321L,
                            Pro_Name = "Dr. Mona",
                            Pro_code = 202,
                            Role = "Professor"
                        },
                        new
                        {
                            Professor_id = 3,
                            Department = "IS",
                            Email = "tarek@gmail.com",
                            Gender = "Male",
                            Password = "tarek456",
                            Phone = 1171222333L,
                            Pro_Name = "Dr. Tarek",
                            Pro_code = 203,
                            Role = "Professor"
                        },
                        new
                        {
                            Professor_id = 4,
                            Department = "CS",
                            Email = "salma@gmail.com",
                            Gender = "Female",
                            Password = "salma789",
                            Phone = 1284555666L,
                            Pro_Name = "Dr. Salma",
                            Pro_code = 204,
                            Role = "Professor"
                        },
                        new
                        {
                            Professor_id = 5,
                            Department = "IT",
                            Email = "mostafa@gmail.com",
                            Gender = "Male",
                            Password = "mostafa000",
                            Phone = 1077888999L,
                            Pro_Name = "Dr. Mostafa",
                            Pro_code = 205,
                            Role = "Professor"
                        },
                        new
                        {
                            Professor_id = 6,
                            Department = "CS",
                            Email = "lina@gmail.com",
                            Gender = "Female",
                            Password = "lina123",
                            Phone = 222333444L,
                            Pro_Name = "Dr. Lina",
                            Pro_code = 206,
                            Role = "Professor"
                        },
                        new
                        {
                            Professor_id = 7,
                            Department = "CS",
                            Email = "hassan@gmail.com",
                            Gender = "Male",
                            Password = "hassan123",
                            Phone = 2333333333L,
                            Pro_Name = "Dr. Hassan",
                            Pro_code = 207,
                            Role = "Professor"
                        },
                        new
                        {
                            Professor_id = 8,
                            Department = "IT",
                            Email = "rania@gmail.com",
                            Gender = "Female",
                            Password = "rania123",
                            Phone = 2444444444L,
                            Pro_Name = "Dr. Rania",
                            Pro_code = 208,
                            Role = "Professor"
                        },
                        new
                        {
                            Professor_id = 9,
                            Department = "IS",
                            Email = "khaled@gmail.com",
                            Gender = "Male",
                            Password = "khaled123",
                            Phone = 2555555555L,
                            Pro_Name = "Dr. Khaled",
                            Pro_code = 209,
                            Role = "Professor"
                        });
                });

            modelBuilder.Entity("Final_Project.Model.Student", b =>
                {
                    b.Property<int>("Student_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_id"));

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Phone")
                        .HasColumnType("bigint");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("St_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("St_code")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Student_id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Student_id = 1,
                            Department = "CS",
                            Email = "mostafa@gmail.com",
                            Gender = "Male",
                            Password = "123456",
                            Phone = 1234567894L,
                            Role = "Student",
                            St_Name = "Mostafa",
                            St_code = 111
                        },
                        new
                        {
                            Student_id = 2,
                            Department = "IT",
                            Email = "sara@gmail.com",
                            Gender = "Female",
                            Password = "abcdef",
                            Phone = 1098765432L,
                            Role = "Student",
                            St_Name = "Sara",
                            St_code = 112
                        },
                        new
                        {
                            Student_id = 3,
                            Department = "CS",
                            Email = "youssef@gmail.com",
                            Gender = "Male",
                            Password = "pass123",
                            Phone = 1112223335L,
                            Role = "Student",
                            St_Name = "Youssef",
                            St_code = 113
                        },
                        new
                        {
                            Student_id = 4,
                            Department = "IS",
                            Email = "nada@gmail.com",
                            Gender = "Female",
                            Password = "nada321",
                            Phone = 1244555666L,
                            Role = "Student",
                            St_Name = "Nada",
                            St_code = 114
                        },
                        new
                        {
                            Student_id = 5,
                            Department = "CS",
                            Email = "ahmed@gmail.com",
                            Gender = "Male",
                            Password = "omar789",
                            Phone = 1577888999L,
                            Role = "Student",
                            St_Name = "Ahmed",
                            St_code = 115
                        },
                        new
                        {
                            Student_id = 6,
                            Department = "IT",
                            Email = "omar@gmail.com",
                            Gender = "Male",
                            Password = "omar123",
                            Phone = 1222333444L,
                            Role = "Student",
                            St_Name = "Omar",
                            St_code = 116
                        },
                        new
                        {
                            Student_id = 7,
                            Department = "CS",
                            Email = "mariam@gmail.com",
                            Gender = "Female",
                            Password = "mariam123",
                            Phone = 1333444555L,
                            Role = "Student",
                            St_Name = "Mariam",
                            St_code = 117
                        },
                        new
                        {
                            Student_id = 8,
                            Department = "IS",
                            Email = "khaled@gmail.com",
                            Gender = "Male",
                            Password = "khaled123",
                            Phone = 1444555666L,
                            Role = "Student",
                            St_Name = "Khaled",
                            St_code = 118
                        },
                        new
                        {
                            Student_id = 9,
                            Department = "CS",
                            Email = "hana@gmail.com",
                            Gender = "Female",
                            Password = "hana123",
                            Phone = 1555666777L,
                            Role = "Student",
                            St_Name = "Hana",
                            St_code = 119
                        },
                        new
                        {
                            Student_id = 10,
                            Department = "IT",
                            Email = "mahmoud@gmail.com",
                            Gender = "Male",
                            Password = "mahmoud123",
                            Phone = 1666777888L,
                            Role = "Student",
                            St_Name = "Mahmoud",
                            St_code = 120
                        },
                        new
                        {
                            Student_id = 11,
                            Department = "CS",
                            Email = "ali@gmail.com",
                            Gender = "Male",
                            Password = "ali123",
                            Phone = 1777888999L,
                            Role = "Student",
                            St_Name = "Ali",
                            St_code = 121
                        },
                        new
                        {
                            Student_id = 12,
                            Department = "IT",
                            Email = "fatma@gmail.com",
                            Gender = "Female",
                            Password = "fatma123",
                            Phone = 1888999000L,
                            Role = "Student",
                            St_Name = "Fatma",
                            St_code = 122
                        },
                        new
                        {
                            Student_id = 13,
                            Department = "IS",
                            Email = "ibrahim@gmail.com",
                            Gender = "Male",
                            Password = "ibrahim123",
                            Phone = 1999000111L,
                            Role = "Student",
                            St_Name = "Ibrahim",
                            St_code = 123
                        },
                        new
                        {
                            Student_id = 14,
                            Department = "CS",
                            Email = "nour@gmail.com",
                            Gender = "Female",
                            Password = "nour123",
                            Phone = 2000111222L,
                            Role = "Student",
                            St_Name = "Nour",
                            St_code = 124
                        },
                        new
                        {
                            Student_id = 15,
                            Department = "IT",
                            Email = "yara@gmail.com",
                            Gender = "Female",
                            Password = "yara123",
                            Phone = 2111222333L,
                            Role = "Student",
                            St_Name = "Yara",
                            St_code = 125
                        },
                        new
                        {
                            Student_id = 16,
                            Department = "CS",
                            Email = "amr@gmail.com",
                            Gender = "Male",
                            Password = "amr123",
                            Phone = 2222333444L,
                            Role = "Student",
                            St_Name = "Amr",
                            St_code = 126
                        },
                        new
                        {
                            Student_id = 17,
                            Department = "IS",
                            Email = "salem@gmail.com",
                            Gender = "Male",
                            Password = "salem123",
                            Phone = 2333444555L,
                            Role = "Student",
                            St_Name = "Salem",
                            St_code = 127
                        },
                        new
                        {
                            Student_id = 18,
                            Department = "CS",
                            Email = "laila@gmail.com",
                            Gender = "Female",
                            Password = "laila123",
                            Phone = 2444555666L,
                            Role = "Student",
                            St_Name = "Laila",
                            St_code = 128
                        },
                        new
                        {
                            Student_id = 19,
                            Department = "IT",
                            Email = "karim@gmail.com",
                            Gender = "Male",
                            Password = "karim123",
                            Phone = 2555666777L,
                            Role = "Student",
                            St_Name = "Karim",
                            St_code = 129
                        },
                        new
                        {
                            Student_id = 20,
                            Department = "CS",
                            Email = "hossam@gmail.com",
                            Gender = "Male",
                            Password = "hossam123",
                            Phone = 2666777888L,
                            Role = "Student",
                            St_Name = "Hossam",
                            St_code = 130
                        });
                });

            modelBuilder.Entity("Final_Project.Model.StudentSubject", b =>
                {
                    b.Property<int?>("Student_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Subject_Id")
                        .HasColumnType("int");

                    b.HasKey("Student_Id", "Subject_Id");

                    b.HasIndex("Subject_Id");

                    b.ToTable("StudentSubjects");

                    b.HasData(
                        new
                        {
                            Student_Id = 1,
                            Subject_Id = 1
                        },
                        new
                        {
                            Student_Id = 1,
                            Subject_Id = 3
                        },
                        new
                        {
                            Student_Id = 2,
                            Subject_Id = 1
                        },
                        new
                        {
                            Student_Id = 2,
                            Subject_Id = 4
                        },
                        new
                        {
                            Student_Id = 3,
                            Subject_Id = 2
                        },
                        new
                        {
                            Student_Id = 3,
                            Subject_Id = 4
                        },
                        new
                        {
                            Student_Id = 4,
                            Subject_Id = 2
                        },
                        new
                        {
                            Student_Id = 4,
                            Subject_Id = 5
                        },
                        new
                        {
                            Student_Id = 5,
                            Subject_Id = 3
                        },
                        new
                        {
                            Student_Id = 5,
                            Subject_Id = 5
                        },
                        new
                        {
                            Student_Id = 11,
                            Subject_Id = 9
                        },
                        new
                        {
                            Student_Id = 12,
                            Subject_Id = 10
                        },
                        new
                        {
                            Student_Id = 13,
                            Subject_Id = 11
                        },
                        new
                        {
                            Student_Id = 14,
                            Subject_Id = 12
                        },
                        new
                        {
                            Student_Id = 15,
                            Subject_Id = 9
                        },
                        new
                        {
                            Student_Id = 16,
                            Subject_Id = 10
                        },
                        new
                        {
                            Student_Id = 17,
                            Subject_Id = 11
                        },
                        new
                        {
                            Student_Id = 18,
                            Subject_Id = 12
                        },
                        new
                        {
                            Student_Id = 19,
                            Subject_Id = 9
                        },
                        new
                        {
                            Student_Id = 20,
                            Subject_Id = 10
                        });
                });

            modelBuilder.Entity("Final_Project.Model.Subject", b =>
                {
                    b.Property<int>("Sub_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sub_ID"));

                    b.Property<int?>("Professor_Id")
                        .HasColumnType("int");

                    b.Property<string>("Sub_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sub_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sub_ID");

                    b.HasIndex("Professor_Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Sub_ID = 1,
                            Professor_Id = 1,
                            Sub_Code = "CS101",
                            Sub_Name = "OOP"
                        },
                        new
                        {
                            Sub_ID = 2,
                            Professor_Id = 4,
                            Sub_Code = "CS102",
                            Sub_Name = "Databases"
                        },
                        new
                        {
                            Sub_ID = 3,
                            Professor_Id = 2,
                            Sub_Code = "IT201",
                            Sub_Name = "Networks"
                        },
                        new
                        {
                            Sub_ID = 4,
                            Professor_Id = 6,
                            Sub_Code = "CS202",
                            Sub_Name = "Algorithms"
                        },
                        new
                        {
                            Sub_ID = 5,
                            Professor_Id = 3,
                            Sub_Code = "IS301",
                            Sub_Name = "Information Security"
                        },
                        new
                        {
                            Sub_ID = 6,
                            Professor_Id = 1,
                            Sub_Code = "CS303",
                            Sub_Name = "Operating Systems"
                        },
                        new
                        {
                            Sub_ID = 7,
                            Professor_Id = 6,
                            Sub_Code = "CS404",
                            Sub_Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Sub_ID = 8,
                            Professor_Id = 2,
                            Sub_Code = "IT305",
                            Sub_Name = "Web Development"
                        },
                        new
                        {
                            Sub_ID = 9,
                            Professor_Id = 7,
                            Sub_Code = "CS405",
                            Sub_Name = "Machine Learning"
                        },
                        new
                        {
                            Sub_ID = 10,
                            Professor_Id = 8,
                            Sub_Code = "IT402",
                            Sub_Name = "Cloud Computing"
                        },
                        new
                        {
                            Sub_ID = 11,
                            Professor_Id = 9,
                            Sub_Code = "IS404",
                            Sub_Name = "Cyber Security"
                        },
                        new
                        {
                            Sub_ID = 12,
                            Professor_Id = 7,
                            Sub_Code = "CS350",
                            Sub_Name = "Software Engineering"
                        });
                });

            modelBuilder.Entity("Final_Project.Model.Attendance", b =>
                {
                    b.HasOne("Final_Project.Model.Professor", "Professor")
                        .WithMany("Attendances")
                        .HasForeignKey("Professor_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Final_Project.Model.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Final_Project.Model.Subject", "Subject")
                        .WithMany("Attendances")
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Final_Project.Model.StudentSubject", b =>
                {
                    b.HasOne("Final_Project.Model.Student", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Final_Project.Model.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Final_Project.Model.Subject", b =>
                {
                    b.HasOne("Final_Project.Model.Professor", "Professor")
                        .WithMany("Subjects")
                        .HasForeignKey("Professor_Id");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Final_Project.Model.Professor", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Final_Project.Model.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("Final_Project.Model.Subject", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("StudentSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
